# SITE CONFIGURATION
title: Raising Millo # your site title
author: Ana Hernandez # You :P
description: > # Meta description of Homepage
  A blog about the challenges and joys of raising a Galician Shepherd puppy dog. Welcome to Millo's world!
# baseurl: "/sleek" # the subpath of your site, e.g. /blog
url: "https://www.raising-millo.com" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Millo
  links:
    - https://twitter.com/RaisingMillo
    - https://www.facebook.com/raising_millo
    - https://www.instagram.com/raising_millo

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}
  - {name: 'Contact', link: '/contact'}

tagline: >
  Raising a Galician Shepherd Dog in the mountains. Welcome to the world of Millo

hero_img: posts/hero_image_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: raisingmillo@gmail.com # email for form submission

twitter_username: RaisingMillo
facebook_username: raisingmillo
instagram_username: raising_millo

disqus:
  shortname: raising-millo # to enable comments replace with your_disqus_shortname

google_tag_manager: GTM-MTZNM6P

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg
  - Dockerfile
  - docker-compose.yml

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
